#spring:
#  profiles:
#    active: dev

server:
  port: 8081
  servlet:
    register-default-servlet: true
    context-path: /

spring:
  datasource:
    username: root
    password: 331520
    url: jdbc:mysql://localhost:3306/luoan_forum?rewriteBatchedStatements=true
    driver-class-name: com.mysql.jdbc.Driver
  mvc:
    static-path-pattern: /static/**
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 50MB
  web:
    resources:
      static-locations: classpath:/META-INF/resources,classpath:/resources,classpath:/static,classpath:/public

static-base-path: C:\Users\17561\IdeaProjects\luoanforum\src\main\resources\resources\
separator: \
host: resources #static
default-limit: 3

token:
  name: token
  timeout: 3600

mybatis:
  configuration:
    map-underscore-to-camel-case: true


  #  mapper-locations: classpath:mapping/*.xml
#  type-aliases-package: com.example.luoanforum:

#logging:
#  level:
#    com.example.luoanforum.mapper: debug