dreams:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/dreams_oauth2?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: 331520
  redis:
    host: localhost
    port: 6379
    password: 331520
  security:
    sign-in-page-uri: /login
    consent-page-uri: /oauth/confirm_access
    device-activate-page-uri: /device/activate
    device-activated-page-uri: /device/activated
    issuer-url: http://localhost:9000
    ignore-uri-list: /assets/**, /webjars/**, /login, /getCaptcha, /getSmsCaptcha, /error, /oauth2/consent/parameters, /test03, /favicon.ico